stages:
  - docker-build
  - test

docker-build:
  stage: docker-build
  image: docker:stable
  services:
    - name: docker:19.03.8-dind
      alias: whoami
  variables:
    DOCKER_HOST: tcp://whoami:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - sudo docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - sudo docker push "$CI_REGISTRY_IMAGE"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"
