image: node:12.14.0

stages:
  - test
  #- build
  #- deploy

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"
