image: node:12.14.0

stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"

include:
  - template: Code-Quality.gitlab-ci.yml