version: "3"
services:
  server:
    container_name: server
    image: whoami-server
    build: .
    stdin_open: true
    working_dir: /home/whoami/server/
    volumes:
      -  whoami-volume:/home/whoami/server
      - .:/home/whoami/server/
    ports:
        - 5000:5001
    restart: always
    networks:
      - mynetwork
  client:
    container_name: c
    image: whoami-c
    build: .\client
    stdin_open: true
    working_dir: /home/whoami/c/
    volumes:
      - whoami-volume:/home/whoami/c/
      - ./client:/home/whoami/c/
    ports:
      - 3006:3006
    depends_on:
      - server
    restart: always
    networks:
      - mynetwork
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true #Required for running docker inside container
    user: root #Required for running various scripts
    ports:
      - 8080:8080
    networks:
      - mynetwork
    volumes:
      - jenkins-data:/var/jenkins_home/
      - C:\Users\chant\apache-jmeter-5.5\:/var/jenkins_home/jmeter/
      - C:\Program Files\OWASP\Zed Attack Proxy\:/var/jenkins_home/zap/
      - C:\Users\chant\OWASP ZAP\:/var/jenkins_home/zap/
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    # Required valid permission for /var/lib/grafana to create files and folders
    # Since I run from the root so both uid and gid are 0:0
    # but you can use the command i.e. (id) without brackets to find your user correct numbers
    user: "0:0"
    ports:
      - 3000:3000
    networks:
      - mynetwork
    volumes:
      - metrics-data:/etc/grafana/provisioning/datasources/
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  prom:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - mynetwork
    volumes:
      - metrics-data:/etc/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

      # fixed the path here as originally you wrote without /etc
      # while in above line you are mentioning /etc/ so was causing errors
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100

networks:
  mynetwork:
volumes:
  metrics-data:
  jenkins-data:
  whoami-volume:
